export function buildAtlasFixture() {
  const generatedAt = '2026-03-09T03:00:00.000Z';

  const data = {
    generatedAt,
    doctrine: {
      slogan: 'Core decides. Projections explain. Apps render.',
      principles: ['contracts-first', 'canonical-write-path', 'projection-canonical'],
    },
    repos: [
      {
        name: 'API',
        loc: 12040,
        routes: [{ path: '/payments' }, { path: '/widgets' }, { path: '/analytics' }],
        tests: [{ kind: 'unit' }, { kind: 'unit' }, { kind: 'e2e' }],
        hotspots: [{ file: 'apps/api/payments/service.py', loc: 2840 }],
        risks: [{ type: 'coupling', severity: 'high', message: 'payments route aggregates local business fallback' }],
        validation: ['npm run test:contracts', 'npm run test:e2e'],
      },
      {
        name: 'SCARABEE',
        loc: 9100,
        routes: [{ path: '/chat' }, { path: '/publications' }],
        tests: [{ kind: 'unit' }, { kind: 'e2e' }],
        hotspots: [{ file: 'src/app/publications/dashboard.tsx', loc: 2100 }],
        risks: [{ type: 'projection', severity: 'medium', message: 'consumer fallback still present on widgets panel' }],
        validation: ['npm run test', 'npm run lint'],
      },
    ],
    gaps: [
      { domain: 'payments', type: 'projection', severity: 'high', message: 'payments projection latency breach' },
      { domain: 'widgets', type: 'ownership', severity: 'medium', message: 'widgets owner escalation pending' },
    ],
    domainProfiles: [
      {
        domain: 'payments',
        overallScore: 68,
        consumers: ['scarabee', 'moniteur'],
        scores: {
          architectureHealth: { score: 65 },
          projectionDiscipline: { score: 62 },
          validationMaturity: { score: 72 },
          extractionReadiness: { score: 55 },
          observabilityReadiness: { score: 70 },
        },
        badges: {
          contractsFirst: 'warn',
          canonicalWritePath: 'fail',
          projectionCanonical: 'warn',
          noDuplicatedBusinessLogic: 'fail',
          otelReady: 'pass',
          pkceReady: 'pass',
          e2eProof: 'warn',
          moduleReady: 'warn',
        },
        evidence: {
          writeSignals: ['core:payments.write'],
          writeOutsideCore: ['ui:payments.fallback'],
          projectionSignals: ['payments_status_v1'],
          driftSignals: ['projection bypass'],
        },
        coreDecidesProjectionRender: {
          coreDecides: 'payments authorization + retries',
          projectionsExplain: 'payments_status_v1',
          appsRenderOnly: 'queue and remediation CTA',
        },
      },
      {
        domain: 'widgets',
        overallScore: 74,
        consumers: ['scarabee'],
        scores: {
          architectureHealth: { score: 72 },
          projectionDiscipline: { score: 70 },
          validationMaturity: { score: 76 },
          extractionReadiness: { score: 68 },
          observabilityReadiness: { score: 73 },
        },
        badges: {
          contractsFirst: 'pass',
          canonicalWritePath: 'warn',
          projectionCanonical: 'pass',
          noDuplicatedBusinessLogic: 'warn',
          otelReady: 'pass',
          pkceReady: 'pass',
          e2eProof: 'warn',
          moduleReady: 'warn',
        },
        evidence: {
          writeSignals: ['core:widgets.write'],
          writeOutsideCore: [],
          projectionSignals: ['widgets_health_v1'],
          driftSignals: ['cross-domain import'],
        },
        coreDecidesProjectionRender: {
          coreDecides: 'widgets lifecycle decisions',
          projectionsExplain: 'widgets_health_v1',
          appsRenderOnly: 'status panel and actions',
        },
      },
      {
        domain: 'analytics',
        overallScore: 91,
        consumers: ['dashboard', 'moniteur', 'abetca'],
        scores: {
          architectureHealth: { score: 90 },
          projectionDiscipline: { score: 92 },
          validationMaturity: { score: 89 },
          extractionReadiness: { score: 85 },
          observabilityReadiness: { score: 92 },
        },
        badges: {
          contractsFirst: 'pass',
          canonicalWritePath: 'pass',
          projectionCanonical: 'pass',
          noDuplicatedBusinessLogic: 'pass',
          otelReady: 'pass',
          pkceReady: 'pass',
          e2eProof: 'pass',
          moduleReady: 'pass',
        },
        evidence: {
          writeSignals: ['core:analytics.write'],
          writeOutsideCore: [],
          projectionSignals: ['analytics_kpi'],
          driftSignals: [],
        },
        coreDecidesProjectionRender: {
          coreDecides: 'analytics KPI aggregation policy',
          projectionsExplain: 'analytics_kpi',
          appsRenderOnly: 'reporting dashboards',
        },
      },
    ],
    projectionRegistry: [
      {
        domain: 'payments',
        projection: 'payments_status_v1',
        consumers: ['scarabee', 'atlas'],
        owner: 'api',
        canonical: true,
        status: 'canonical',
      },
      {
        domain: 'widgets',
        projection: 'widgets_health_v1',
        consumers: ['scarabee', 'atlas'],
        owner: 'api',
        canonical: true,
        status: 'canonical',
      },
      {
        domain: 'analytics',
        projection: 'analytics_kpi',
        consumers: ['dashboard', 'moniteur', 'abetca'],
        owner: 'api',
        canonical: true,
        status: 'canonical',
      },
    ],
    domainOwnership: [
      { domain: 'payments', owner: 'team-payments', consumers: ['scarabee', 'moniteur'], projections: ['payments_status_v1'] },
      { domain: 'widgets', owner: 'team-widgets', consumers: ['scarabee'], projections: ['widgets_health_v1'] },
      { domain: 'analytics', owner: 'team-analytics', consumers: ['dashboard', 'moniteur', 'abetca'], projections: ['analytics_kpi'] },
    ],
    externalServices: [
      { service: 'Stripe', repos: ['API'], domains: ['payments'], humanOnlyRisk: false, maturity: 'managed' },
      { service: 'SendGrid', repos: ['SCARABEE'], domains: ['widgets'], humanOnlyRisk: true, maturity: 'partial' },
    ],
    roadmap: [
      {
        label: 'Stabiliser projection payments',
        domain: 'payments',
        ticket: 'MBE-2101',
        readiness: 82,
        status: 'in-progress',
        notes: ['contract tests pass', 'queue active'],
      },
      {
        label: 'Extract widgets orchestration',
        domain: 'widgets',
        ticket: 'MBE-2102',
        readiness: 63,
        status: 'todo',
        notes: ['depends e2e suite'],
      },
      {
        label: 'Hold analytics baseline',
        domain: 'analytics',
        ticket: 'MBE-2103',
        readiness: 91,
        status: 'done',
        notes: ['reference domain'],
      },
    ],
    graph: {
      nodes: [
        { id: 'repo:api', type: 'repo', label: 'api' },
        { id: 'repo:scarabee', type: 'repo', label: 'scarabee' },
        { id: 'domain:payments', type: 'domain', label: 'payments' },
        { id: 'domain:widgets', type: 'domain', label: 'widgets' },
        { id: 'domain:analytics', type: 'domain', label: 'analytics' },
        { id: 'projection:payments', type: 'projection', label: 'payments_status_v1' },
        { id: 'projection:widgets', type: 'projection', label: 'widgets_health_v1' },
        { id: 'projection:analytics', type: 'projection', label: 'analytics_kpi' },
        { id: 'provider:stripe', type: 'provider', label: 'Stripe' },
      ],
      edges: [
        { from: 'repo:api', to: 'domain:payments', kind: 'owns' },
        { from: 'repo:api', to: 'domain:widgets', kind: 'owns' },
        { from: 'repo:scarabee', to: 'domain:widgets', kind: 'consumer' },
        { from: 'domain:payments', to: 'projection:payments', kind: 'read-model' },
        { from: 'domain:widgets', to: 'projection:widgets', kind: 'read-model' },
        { from: 'domain:analytics', to: 'projection:analytics', kind: 'read-model' },
        { from: 'domain:payments', to: 'provider:stripe', kind: 'integration' },
      ],
    },
    decisionPriority: {
      generatedAt,
      domains: [
        {
          domain: 'payments',
          score: 84.2,
          rank: 1,
          signals: {
            strategicImportance: 92,
            driftFindings: 4,
            policyViolationCount: 2,
            crossDomainImports: 3,
            consumers: 2,
            gapCount: 2,
            currentScore: 68,
            projectedScore: 59,
          },
        },
        {
          domain: 'widgets',
          score: 71.4,
          rank: 2,
          signals: {
            strategicImportance: 76,
            driftFindings: 2,
            policyViolationCount: 1,
            crossDomainImports: 2,
            consumers: 1,
            gapCount: 1,
            currentScore: 74,
            projectedScore: 67,
          },
        },
        {
          domain: 'analytics',
          score: 34.9,
          rank: 3,
          signals: {
            strategicImportance: 74,
            driftFindings: 0,
            policyViolationCount: 0,
            crossDomainImports: 0,
            consumers: 3,
            gapCount: 0,
            currentScore: 91,
            projectedScore: 90,
          },
        },
      ],
      alerts: [
        { id: 'alert:payments:stale', score: 96.1 },
        { id: 'alert:widgets:drift', score: 79.4 },
        { id: 'alert:analytics:watch', score: 35.4 },
      ],
    },
    alertsTaxonomy: {
      generatedAt,
      alerts: [
        {
          id: 'alert:payments:stale',
          type: 'snapshot-stale',
          domain: 'payments',
          owner: 'team-payments',
          severity: 'high',
          explanation: 'Snapshot payments stale depuis 52h',
          action: 'Relancer ingestion payments et revalider la projection.',
          projectedImpact: 'Décision potentiellement obsolète',
          proofLink: 'data/history/atlas-snapshot-payments.json',
          state: 'open',
          priorityScore: 96.1,
          sourceFile: 'data/atlas-data.json',
          sourcePath: 'alertsTaxonomy.alerts[0]',
        },
        {
          id: 'alert:widgets:drift',
          type: 'domain-drift',
          domain: 'widgets',
          owner: 'team-widgets',
          severity: 'medium',
          explanation: 'Cross-domain import détecté sur widgets',
          action: 'Extraire dépendance vers projection canonique.',
          projectedImpact: 'Couplage croissant',
          proofLink: 'data/architecture-drift.json',
          state: 'in-progress',
          priorityScore: 79.4,
          sourceFile: 'data/architecture-drift.json',
          sourcePath: 'domains.widgets',
        },
        {
          id: 'alert:analytics:watch',
          type: 'watch',
          domain: 'analytics',
          owner: 'team-analytics',
          severity: 'low',
          explanation: 'Domaine stable à monitorer',
          action: 'Maintenir discipline et revue hebdomadaire.',
          projectedImpact: 'Faible',
          proofLink: 'data/atlas-history.json',
          state: 'done',
          priorityScore: 35.4,
          sourceFile: 'data/atlas-history.json',
          sourcePath: 'trendsCorrelation',
        },
      ],
    },
    freshnessContract: {
      generatedAt,
      slaHours: { normal: 24, degraded: 48 },
      globalStatus: 'normal',
      staleDatasetCount: 0,
      datasets: [
        {
          dataset: 'atlas-data',
          file: 'data/atlas-data.json',
          generatedAt,
          ageHours: 6.1,
          status: 'normal',
        },
      ],
      alerts: [],
    },
  };

  const architectureScore = {
    generatedAt,
    domains: [
      {
        domain: 'payments',
        overall: 68,
        architectureHealth: 65,
        projectionDiscipline: 62,
        validationMaturity: 72,
        warnings: ['write-path duplication'],
      },
      {
        domain: 'widgets',
        overall: 74,
        architectureHealth: 72,
        projectionDiscipline: 70,
        validationMaturity: 76,
        warnings: ['cross-domain import'],
      },
      {
        domain: 'analytics',
        overall: 91,
        architectureHealth: 90,
        projectionDiscipline: 92,
        validationMaturity: 89,
        warnings: [],
      },
    ],
  };

  const driftReport = {
    summary: {
      domainsWithDrift: 2,
      totalFindings: 6,
      criticalDomains: [
        {
          domain: 'payments',
          riskLevel: 'high',
          totalFindings: 4,
          projectedScore: 59,
        },
      ],
    },
    domains: {
      payments: {
        totalFindings: 4,
        projectionBypassCount: 1,
        unregisteredEvents: 1,
        undeclaredProjections: 1,
        ownershipViolations: 1,
        unauthorizedConsumerReads: 0,
        crossDomainImports: 3,
        riskLevel: 'high',
        healthImpact: { projectedScore: 59 },
      },
      widgets: {
        totalFindings: 2,
        projectionBypassCount: 0,
        unregisteredEvents: 0,
        undeclaredProjections: 1,
        ownershipViolations: 1,
        unauthorizedConsumerReads: 0,
        crossDomainImports: 2,
        riskLevel: 'medium',
        healthImpact: { projectedScore: 67 },
      },
      analytics: {
        totalFindings: 0,
        projectionBypassCount: 0,
        unregisteredEvents: 0,
        undeclaredProjections: 0,
        ownershipViolations: 0,
        unauthorizedConsumerReads: 0,
        crossDomainImports: 0,
        riskLevel: 'low',
        healthImpact: { projectedScore: 90 },
      },
    },
  };

  const history = {
    snapshots: [
      {
        generatedAt: '2026-03-08T00:00:00.000Z',
        file: 'history/atlas-snapshot-1.json',
        summary: {
          domainScores: { payments: 72, widgets: 75, analytics: 90 },
          gapCount: 3,
          servicesCount: 2,
          graphNodes: 8,
          graphEdges: 6,
          domainCount: 3,
        },
      },
      {
        generatedAt: '2026-03-09T00:00:00.000Z',
        file: 'history/atlas-snapshot-2.json',
        summary: {
          domainScores: { payments: 68, widgets: 74, analytics: 91 },
          gapCount: 2,
          servicesCount: 2,
          graphNodes: 9,
          graphEdges: 7,
          domainCount: 3,
        },
      },
    ],
    trendsCorrelation: {
      generatedAt,
      windows: {
        '7d': {
          fromGeneratedAt: '2026-03-02T00:00:00.000Z',
          toGeneratedAt: '2026-03-09T00:00:00.000Z',
          deltas: { avgScoreDelta: -1.8, gapDelta: -1, graphEdgesDelta: 1 },
          impactLevel: 'medium',
          impactScore: 58,
          causalRead: 'payments degradation linked to stale snapshot + coupling.',
        },
        '30d': {
          fromGeneratedAt: '2026-02-08T00:00:00.000Z',
          toGeneratedAt: '2026-03-09T00:00:00.000Z',
          deltas: { avgScoreDelta: -3.9, gapDelta: 1, graphEdgesDelta: 2 },
          impactLevel: 'high',
          impactScore: 74,
          causalRead: 'long trend confirms payments and widgets drift pressure.',
        },
        '90d': {
          fromGeneratedAt: '2025-12-09T00:00:00.000Z',
          toGeneratedAt: '2026-03-09T00:00:00.000Z',
          deltas: { avgScoreDelta: -1.2, gapDelta: 0, graphEdgesDelta: 1 },
          impactLevel: 'medium',
          impactScore: 52,
          causalRead: 'overall stable except concentrated payments risk.',
        },
      },
      notableEvents: [
        {
          timestamp: '2026-03-09T00:00:00.000Z',
          whatChanged: 'payments stale alert promoted to queue top-1',
          impactLevel: 'high',
          impactScore: 74,
          signals: { avgScoreDelta: -1.8, gapDelta: -1, graphEdgesDelta: 1 },
          source: { currentSnapshotFile: 'history/atlas-snapshot-2.json' },
        },
      ],
      domainWindows: {
        payments: { '7d': { scoreDelta: -4 }, '30d': { scoreDelta: -6 }, '90d': { scoreDelta: -3 } },
        widgets: { '7d': { scoreDelta: -1 }, '30d': { scoreDelta: -2 }, '90d': { scoreDelta: -1 } },
        analytics: { '7d': { scoreDelta: 1 }, '30d': { scoreDelta: 2 }, '90d': { scoreDelta: 1 } },
      },
    },
  };

  const auditIndex = {
    generatedAt,
    artifacts: [
      {
        id: 'dataset:atlas-data',
        type: 'dataset',
        source: 'generated',
        label: 'Dataset Atlas principal',
        path: 'data/atlas-data.json',
        generatedAt,
        sizeBytes: 42000,
        domain: 'platform',
      },
      {
        id: 'dataset:atlas-history',
        type: 'dataset',
        source: 'generated',
        label: 'Historique Atlas',
        path: 'data/atlas-history.json',
        generatedAt,
        sizeBytes: 9000,
        domain: 'platform',
      },
      {
        id: 'snapshot:history/atlas-snapshot-1.json',
        type: 'snapshot',
        source: 'history',
        label: 'Snapshot brut 1',
        path: 'data/history/atlas-snapshot-1.json',
        generatedAt: '2026-03-08T00:00:00.000Z',
        sizeBytes: 18000,
        domain: 'platform',
      },
      {
        id: 'snapshot:history/atlas-snapshot-2.json',
        type: 'snapshot',
        source: 'history',
        label: 'Snapshot brut 2',
        path: 'data/history/atlas-snapshot-2.json',
        generatedAt: '2026-03-09T00:00:00.000Z',
        sizeBytes: 19500,
        domain: 'platform',
      },
    ],
  };

  const serviceOpsReport = {
    generatedAt,
    decisionKpis: {
      version: 'v1',
      generatedAt,
      source: 'Atlas UI local telemetry',
      targets: {
        timeToFirstPrioritySec: 30,
        timeToRationaleSec: 60,
        clicksToOwnerAction: 2,
        drilldownRateMin: 0.25,
      },
      baselineBeforeRefactor: {
        sampleSize: 18,
        timeToFirstPrioritySec: 86.4,
        timeToRationaleSec: 142.6,
        clicksToOwnerAction: 5.8,
        drilldownRate: 0.18,
      },
      postRefactorBaseline: {
        sampleSize: 20,
        timeToFirstPrioritySec: 34.1,
        timeToRationaleSec: 63.8,
        clicksToOwnerAction: 2.4,
        drilldownRate: 0.29,
      },
    },
  };

  const previousSnapshot = {
    generatedAt: '2026-03-08T00:00:00.000Z',
    repos: [
      { name: 'API', loc: 11900, routes: [{ path: '/payments' }], tests: [{ kind: 'unit' }, { kind: 'e2e' }] },
      { name: 'SCARABEE', loc: 9050, routes: [{ path: '/chat' }], tests: [{ kind: 'unit' }] },
    ],
    gaps: [{ domain: 'payments', type: 'projection', severity: 'high', message: 'legacy' }],
    graph: { nodes: [{ id: 'repo:api' }], edges: [] },
    externalServices: [{ service: 'Stripe' }],
  };

  return {
    data,
    architectureScore,
    driftReport,
    history,
    auditIndex,
    serviceOpsReport,
    previousSnapshot,
  };
}
